#!/bin/sh
#
# Use this script to regenerate the Protocol Buffer and gRPC files
# needed to build the example.
#
# Note that it requires protoc, protoc-gen-swift, and
# protoc-gen-swiftgrpc binaries.

if [ ! -d "googleapis" ]; then
  curl -L -O https://github.com/googleapis/googleapis/archive/master.zip
  unzip master.zip
  rm -f master.zip
  mv googleapis-master googleapis
fi

protoc \
 	google/cloud/speech/v1p1beta1/cloud_speech.proto \
	google/longrunning/operations.proto \
	google/rpc/status.proto \
	google/rpc/code.proto \
	google/rpc/error_details.proto \
	google/api/annotations.proto \
	google/api/http.proto \
	google/protobuf/descriptor.proto \
 	-Igoogleapis \
	-Iinclude \
	--swift_out=googleapis \
	--swiftgrpc_out=googleapis

# move Swift files to the sources directory
find googleapis -name "*.swift" -exec mv {} SpeechTimestamper \;
