//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: google/longrunning/operations.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol Google_Longrunning_OperationsListOperationsCall: ClientCallUnary {}

fileprivate final class Google_Longrunning_OperationsListOperationsCallBase: ClientCallUnaryBase<Google_Longrunning_ListOperationsRequest, Google_Longrunning_ListOperationsResponse>, Google_Longrunning_OperationsListOperationsCall {
  override class var method: String { return "/google.longrunning.Operations/ListOperations" }
}

internal protocol Google_Longrunning_OperationsGetOperationCall: ClientCallUnary {}

fileprivate final class Google_Longrunning_OperationsGetOperationCallBase: ClientCallUnaryBase<Google_Longrunning_GetOperationRequest, Google_Longrunning_Operation>, Google_Longrunning_OperationsGetOperationCall {
  override class var method: String { return "/google.longrunning.Operations/GetOperation" }
}

internal protocol Google_Longrunning_OperationsDeleteOperationCall: ClientCallUnary {}

fileprivate final class Google_Longrunning_OperationsDeleteOperationCallBase: ClientCallUnaryBase<Google_Longrunning_DeleteOperationRequest, SwiftProtobuf.Google_Protobuf_Empty>, Google_Longrunning_OperationsDeleteOperationCall {
  override class var method: String { return "/google.longrunning.Operations/DeleteOperation" }
}

internal protocol Google_Longrunning_OperationsCancelOperationCall: ClientCallUnary {}

fileprivate final class Google_Longrunning_OperationsCancelOperationCallBase: ClientCallUnaryBase<Google_Longrunning_CancelOperationRequest, SwiftProtobuf.Google_Protobuf_Empty>, Google_Longrunning_OperationsCancelOperationCall {
  override class var method: String { return "/google.longrunning.Operations/CancelOperation" }
}


/// Instantiate Google_Longrunning_OperationsServiceClient, then call methods of this protocol to make API calls.
internal protocol Google_Longrunning_OperationsService: ServiceClient {
  /// Synchronous. Unary.
  func listOperations(_ request: Google_Longrunning_ListOperationsRequest) throws -> Google_Longrunning_ListOperationsResponse
  /// Asynchronous. Unary.
  func listOperations(_ request: Google_Longrunning_ListOperationsRequest, completion: @escaping (Google_Longrunning_ListOperationsResponse?, CallResult) -> Void) throws -> Google_Longrunning_OperationsListOperationsCall

  /// Synchronous. Unary.
  func getOperation(_ request: Google_Longrunning_GetOperationRequest) throws -> Google_Longrunning_Operation
  /// Asynchronous. Unary.
  func getOperation(_ request: Google_Longrunning_GetOperationRequest, completion: @escaping (Google_Longrunning_Operation?, CallResult) -> Void) throws -> Google_Longrunning_OperationsGetOperationCall

  /// Synchronous. Unary.
  func deleteOperation(_ request: Google_Longrunning_DeleteOperationRequest) throws -> SwiftProtobuf.Google_Protobuf_Empty
  /// Asynchronous. Unary.
  func deleteOperation(_ request: Google_Longrunning_DeleteOperationRequest, completion: @escaping (SwiftProtobuf.Google_Protobuf_Empty?, CallResult) -> Void) throws -> Google_Longrunning_OperationsDeleteOperationCall

  /// Synchronous. Unary.
  func cancelOperation(_ request: Google_Longrunning_CancelOperationRequest) throws -> SwiftProtobuf.Google_Protobuf_Empty
  /// Asynchronous. Unary.
  func cancelOperation(_ request: Google_Longrunning_CancelOperationRequest, completion: @escaping (SwiftProtobuf.Google_Protobuf_Empty?, CallResult) -> Void) throws -> Google_Longrunning_OperationsCancelOperationCall

}

internal final class Google_Longrunning_OperationsServiceClient: ServiceClientBase, Google_Longrunning_OperationsService {
  /// Synchronous. Unary.
  internal func listOperations(_ request: Google_Longrunning_ListOperationsRequest) throws -> Google_Longrunning_ListOperationsResponse {
    return try Google_Longrunning_OperationsListOperationsCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func listOperations(_ request: Google_Longrunning_ListOperationsRequest, completion: @escaping (Google_Longrunning_ListOperationsResponse?, CallResult) -> Void) throws -> Google_Longrunning_OperationsListOperationsCall {
    return try Google_Longrunning_OperationsListOperationsCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getOperation(_ request: Google_Longrunning_GetOperationRequest) throws -> Google_Longrunning_Operation {
    return try Google_Longrunning_OperationsGetOperationCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getOperation(_ request: Google_Longrunning_GetOperationRequest, completion: @escaping (Google_Longrunning_Operation?, CallResult) -> Void) throws -> Google_Longrunning_OperationsGetOperationCall {
    return try Google_Longrunning_OperationsGetOperationCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func deleteOperation(_ request: Google_Longrunning_DeleteOperationRequest) throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try Google_Longrunning_OperationsDeleteOperationCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func deleteOperation(_ request: Google_Longrunning_DeleteOperationRequest, completion: @escaping (SwiftProtobuf.Google_Protobuf_Empty?, CallResult) -> Void) throws -> Google_Longrunning_OperationsDeleteOperationCall {
    return try Google_Longrunning_OperationsDeleteOperationCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func cancelOperation(_ request: Google_Longrunning_CancelOperationRequest) throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try Google_Longrunning_OperationsCancelOperationCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func cancelOperation(_ request: Google_Longrunning_CancelOperationRequest, completion: @escaping (SwiftProtobuf.Google_Protobuf_Empty?, CallResult) -> Void) throws -> Google_Longrunning_OperationsCancelOperationCall {
    return try Google_Longrunning_OperationsCancelOperationCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
/// If one of the methods returning `ServerStatus?` returns nil,
/// it is expected that you have already returned a status to the client by means of `session.close`.
internal protocol Google_Longrunning_OperationsProvider: ServiceProvider {
  func listOperations(request: Google_Longrunning_ListOperationsRequest, session: Google_Longrunning_OperationsListOperationsSession) throws -> Google_Longrunning_ListOperationsResponse
  func getOperation(request: Google_Longrunning_GetOperationRequest, session: Google_Longrunning_OperationsGetOperationSession) throws -> Google_Longrunning_Operation
  func deleteOperation(request: Google_Longrunning_DeleteOperationRequest, session: Google_Longrunning_OperationsDeleteOperationSession) throws -> SwiftProtobuf.Google_Protobuf_Empty
  func cancelOperation(request: Google_Longrunning_CancelOperationRequest, session: Google_Longrunning_OperationsCancelOperationSession) throws -> SwiftProtobuf.Google_Protobuf_Empty
}

extension Google_Longrunning_OperationsProvider {
  internal var serviceName: String { return "google.longrunning.Operations" }

  /// Determines and calls the appropriate request handler, depending on the request's method.
  /// Throws `HandleMethodError.unknownMethod` for methods not handled by this service.
  internal func handleMethod(_ method: String, handler: Handler) throws -> ServerStatus? {
    switch method {
    case "/google.longrunning.Operations/ListOperations":
      return try Google_Longrunning_OperationsListOperationsSessionBase(
        handler: handler,
        providerBlock: { try self.listOperations(request: $0, session: $1 as! Google_Longrunning_OperationsListOperationsSessionBase) })
          .run()
    case "/google.longrunning.Operations/GetOperation":
      return try Google_Longrunning_OperationsGetOperationSessionBase(
        handler: handler,
        providerBlock: { try self.getOperation(request: $0, session: $1 as! Google_Longrunning_OperationsGetOperationSessionBase) })
          .run()
    case "/google.longrunning.Operations/DeleteOperation":
      return try Google_Longrunning_OperationsDeleteOperationSessionBase(
        handler: handler,
        providerBlock: { try self.deleteOperation(request: $0, session: $1 as! Google_Longrunning_OperationsDeleteOperationSessionBase) })
          .run()
    case "/google.longrunning.Operations/CancelOperation":
      return try Google_Longrunning_OperationsCancelOperationSessionBase(
        handler: handler,
        providerBlock: { try self.cancelOperation(request: $0, session: $1 as! Google_Longrunning_OperationsCancelOperationSessionBase) })
          .run()
    default:
      throw HandleMethodError.unknownMethod
    }
  }
}

internal protocol Google_Longrunning_OperationsListOperationsSession: ServerSessionUnary {}

fileprivate final class Google_Longrunning_OperationsListOperationsSessionBase: ServerSessionUnaryBase<Google_Longrunning_ListOperationsRequest, Google_Longrunning_ListOperationsResponse>, Google_Longrunning_OperationsListOperationsSession {}

internal protocol Google_Longrunning_OperationsGetOperationSession: ServerSessionUnary {}

fileprivate final class Google_Longrunning_OperationsGetOperationSessionBase: ServerSessionUnaryBase<Google_Longrunning_GetOperationRequest, Google_Longrunning_Operation>, Google_Longrunning_OperationsGetOperationSession {}

internal protocol Google_Longrunning_OperationsDeleteOperationSession: ServerSessionUnary {}

fileprivate final class Google_Longrunning_OperationsDeleteOperationSessionBase: ServerSessionUnaryBase<Google_Longrunning_DeleteOperationRequest, SwiftProtobuf.Google_Protobuf_Empty>, Google_Longrunning_OperationsDeleteOperationSession {}

internal protocol Google_Longrunning_OperationsCancelOperationSession: ServerSessionUnary {}

fileprivate final class Google_Longrunning_OperationsCancelOperationSessionBase: ServerSessionUnaryBase<Google_Longrunning_CancelOperationRequest, SwiftProtobuf.Google_Protobuf_Empty>, Google_Longrunning_OperationsCancelOperationSession {}

